# Generated by Django 4.0 on 2021-12-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('book', '0011_delete_rentedbooks'),
        ('main', '0003_rentedbooks_favoritebooks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteBooks',
            new_name='FavoriteBook',
        ),
        migrations.RenameModel(
            old_name='RentedBooks',
            new_name='RentedBook',
        ),
    ]
