# Generated by Django 4.0 on 2021-12-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_favoritebooks_favoritebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='moderator',
        ),
    ]
