# Generated by Django 4.0 on 2021-12-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_moderator_moderator'),
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedbook',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderator.moderator'),
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
