# Generated by Django 4.0 on 2022-01-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_book_cover_img'),
        ('main', '0008_remove_issuedbook_fine_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritebook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book', unique=True),
        ),
    ]
