# Generated by Django 4.0 on 2021-12-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(max_length=20, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('pages_no', models.IntegerField(max_length=4)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('publish_date', models.DateField()),
                ('edition', models.IntegerField(max_length=11)),
                ('total_quantity', models.IntegerField(max_length=11)),
                ('rented_count', models.IntegerField(max_length=11)),
                ('content_table_img', models.TextField(max_length=500)),
                ('cover_img', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
