# Generated by Django 4.0 on 2021-12-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content_table_img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='rented_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_quantity',
            field=models.IntegerField(),
        ),
    ]
