# Generated by Django 4.0 on 2021-12-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_content_table_img_alter_book_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content_table_img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rented_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
