# Generated by Django 4.0 on 2021-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_content_table_img_alter_book_cover_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rented_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
