# Generated by Django 4.0 on 2021-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_rented_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rented_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
