# Generated by Django 4.0 on 2021-12-15 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_rented_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/media/book/covers'),
            preserve_default=False,
        ),
    ]
