# Generated by Django 4.0 on 2021-12-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content_table_img',
        ),
        migrations.AddField(
            model_name='book',
            name='contents',
            field=models.FileField(null=True, upload_to='static/media/book/contents'),
        ),
    ]
