# Generated by Django 4.0 on 2021-12-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_delete_rentedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
