# Generated by Django 4.0 on 2021-12-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
