# Generated by Django 4.0 on 2021-12-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Arts & Music', 'Arts & Music'), ('Biographies', 'Biographies'), ('Business', 'Business'), ('Comics', 'Comics'), ('Computer & Tech', 'Computer & Tech'), ('Cooking', 'Cooking'), ('Entertainment', 'Entertainment'), ('History', 'History'), ('Literature', 'Literature'), ('Medical', 'Medical'), ('Religion', 'Religion'), ('Science & Math', 'Science & Math'), ('Social Science', 'Social Science'), ('Sports', 'Sports')], max_length=200, null=True),
        ),
    ]
