# Generated by Django 4.0 on 2021-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contents',
            field=models.FileField(blank=True, null=True, upload_to='static/media/book/contents'),
        ),
    ]
