# Generated by Django 4.0 on 2021-12-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
        ('book', '0018_book_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderator.moderator'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/book/covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rented_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
