# Generated by Django 4.0 on 2022-01-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_alter_book_added_by_alter_book_cover_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(blank=True, default='static/media/default_cover.png', null=True, upload_to='static/media/book/covers'),
        ),
    ]
