# Generated by Django 4.0 on 2022-01-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_book_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default='others', null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bookcategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_quantity',
            field=models.IntegerField(default=200, null=True),
        ),
    ]
