# Generated by Django 4.0 on 2022-01-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_keywords_book_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='keywords',
        ),
    ]
