# Generated by Django 4.0 on 2022-01-16 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
