# Generated by Django 4.0 on 2022-01-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_keywords_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Tag',
        ),
    ]
