# Generated by Django 4.0 on 2022-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_rename_keywords_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='category',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
