# Generated by Django 4.0 on 2022-04-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_alter_bookcategory_category_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(unique=True),
        ),
    ]
