# Generated by Django 4.0 on 2021-12-21 09:38

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('graduation_year', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('email_verified', models.IntegerField(default=0, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='static/media/users/qr_codes')),
                ('approved', models.IntegerField(default=0, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default='static/media/users/default.jpg', null=True, upload_to=student.models.Student.student_profile_url)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
