# Generated by Django 4.0 on 2021-12-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_clg_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
