# Generated by Django 4.0 on 2021-12-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
