# Generated by Django 4.0 on 2021-12-31 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_rename_moderator_moderator_user_and_more'),
        ('student', '0006_remove_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderator.moderator'),
        ),
    ]
