# Generated by Django 4.0 on 2021-12-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email_verified',
            new_name='email_verification',
        ),
    ]
