# Generated by Django 4.0 on 2021-12-22 05:48

from django.db import migrations, models
import django.db.models.deletion
import moderator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('email_verification', models.IntegerField(default=0, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(default='static/media/users/default.jpg', null=True, upload_to=moderator.models.Moderator.moderator_profile_url)),
                ('moderator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
