# Generated by Django 4.0 on 2021-12-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='password',
        ),
    ]
